/* eslint-disable */
// This file is automatically generated by OneAPI, please do not modify it manually!

declare namespace API {
  interface PageInfo {
    /** 
1 */
    current?: number;
    pageSize?: number;
    total?: number;
    list?: Array<Record<string, any>>;
  }

  interface PageInfo_UserInfo_ {
    /** 
1 */
    current?: number;
    pageSize?: number;
    total?: number;
    list?: Array<UserInfo>;
  }

  interface Result {
    success?: boolean;
    errorMessage?: string;
    data?: Record<string, any>;
  }

  interface Result_PageInfo_UserInfo__ {
    success?: boolean;
    errorMessage?: string;
    data?: PageInfo_UserInfo_;
  }

  interface Result_UserInfo_ {
    success?: boolean;
    errorMessage?: string;
    data?: UserInfo;
  }

  interface Result_string_ {
    success?: boolean;
    errorMessage?: string;
    data?: string;
  }

  type UserGenderEnum = 'MALE' | 'FEMALE';

  interface UserInfo {
    id?: string;
    name?: string;
    /** nick */
    nickName?: string;
    /** email */
    email?: string;
    gender?: UserGenderEnum;
  }

  interface UserInfoVO {
    name?: string;
    /** nick */
    nickName?: string;
    /** email */
    email?: string;
  }

  type definitions_0 = null;

  type ServiceTypeEnum = 'txt2img' | 'img2img';

  type Service = {
    id?: number;
    name: string;
    code: string;
    description?: string;
    type: ServiceTypeEnum;
  };

  interface ServiceVO {
    name: string;
    code: string;
    description?: string;
    type: ServiceTypeEnum;
  }

  interface PageInfo_Service_ {
    current?: number;
    pageSize?: number;
    total?: number;
    list?: Array<Service>;
  }

  interface Result_PageInfo_Service__ {
    success?: boolean;
    errorMessage?: string;
    data?: PageInfo_Service_;
  }

  interface Result_Service_ {
    success?: boolean;
    errorMessage?: string;
    data?: Service;
  }
}
